// This file was autogenerated by PeakRDL-uvm
package reg_top_reg_model;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - reg_block_prac::ctrl
    class reg_block_prac__ctrl extends uvm_reg;
        rand uvm_reg_field enable;
        rand uvm_reg_field mode;
        rand uvm_reg_field rsvd;

        function new(string name = "reg_block_prac__ctrl");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.enable = new("enable");
            this.enable.configure(this, 1, 0, "RW", 1, 'h0, 0, 1, 0);
            this.mode = new("mode");
            this.mode.configure(this, 2, 1, "RW", 1, 'h0, 0, 1, 0);
            this.rsvd = new("rsvd");
            this.rsvd.configure(this, 29, 3, "RO", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : reg_block_prac__ctrl

    // Reg - reg_block_prac::status
    class reg_block_prac__status extends uvm_reg;
        rand uvm_reg_field ready;
        rand uvm_reg_field error;
        rand uvm_reg_field rsvd;

        function new(string name = "reg_block_prac__status");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ready = new("ready");
            this.ready.configure(this, 1, 0, "RO", 1, 'h0, 0, 1, 0);
            this.error = new("error");
            this.error.configure(this, 1, 1, "RO", 1, 'h0, 0, 1, 0);
            this.rsvd = new("rsvd");
            this.rsvd.configure(this, 30, 2, "RO", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : reg_block_prac__status

    // Reg - reg_block_prac::config
    class reg_block_prac__config extends uvm_reg;
        rand uvm_reg_field cfg0;
        rand uvm_reg_field cfg1;
        rand uvm_reg_field rsvd;

        function new(string name = "reg_block_prac__config");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.cfg0 = new("cfg0");
            this.cfg0.configure(this, 8, 0, "RW", 1, 'h0, 0, 1, 0);
            this.cfg1 = new("cfg1");
            this.cfg1.configure(this, 8, 8, "RW", 1, 'h0, 0, 1, 0);
            this.rsvd = new("rsvd");
            this.rsvd.configure(this, 16, 16, "RO", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : reg_block_prac__config

    // Reg - reg_block_prac::data
    class reg_block_prac__data extends uvm_reg;
        rand uvm_reg_field data;

        function new(string name = "reg_block_prac__data");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.data = new("data");
            this.data.configure(this, 32, 0, "RW", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : reg_block_prac__data

    // Addrmap - reg_block_prac
    class reg_block_prac extends uvm_reg_block;
        rand reg_block_prac__ctrl ctrl;
        rand reg_block_prac__status status;
        rand reg_block_prac__config config;
        rand reg_block_prac__data data;

        function new(string name = "reg_block_prac");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.ctrl = new("ctrl");
            this.ctrl.configure(this);

            this.ctrl.build();
            this.default_map.add_reg(this.ctrl, 'h0);
            this.status = new("status");
            this.status.configure(this);

            this.status.build();
            this.default_map.add_reg(this.status, 'h4);
            this.config = new("config");
            this.config.configure(this);

            this.config.build();
            this.default_map.add_reg(this.config, 'h8);
            this.data = new("data");
            this.data.configure(this);

            this.data.build();
            this.default_map.add_reg(this.data, 'hc);
        endfunction : build
    endclass : reg_block_prac

    // Addrmap - my_block
    class my_block extends uvm_reg_block;
        rand reg_block_prac csr_prac;

        function new(string name = "my_block");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.csr_prac = new("csr_prac");
            this.csr_prac.configure(this);
            this.csr_prac.build();
            this.default_map.add_submap(this.csr_prac.default_map, 'h0);
        endfunction : build
    endclass : my_block

endpackage: reg_top_reg_model
